let a = 2;

try {
    console.log(`a + b: ${a + b}`)
} catch(e) {
    console.log(`Ocoreu o seguinte erro: ${e}`)
} finally {
    console.log(`Apesar do erro, tamo a√≠ na atividade 8)`);
}